site_name:        RRRMC.jl
repo_url:         https://github.com/carlobaldassi/RRRMC.jl
site_description: Julia package RRRMC.jl
site_author:      Carlo Baldassi

theme: readthedocs

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

docs_dir: 'build'

pages:
  - Home: index.md
  - Sampling Algorithms: algorithms.md
  - Graph Types: graph-types.md
  - Built-in Graphs: graphs-builtin.md
  - Graphs Interface: interface.md
